/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedVocabLangRouteImport } from './routes/_authenticated/vocab.$lang'
import { Route as AuthenticatedVideosLangRouteImport } from './routes/_authenticated/videos.$lang'
import { Route as AuthenticatedVideoIdRouteImport } from './routes/_authenticated/video.$id'
import { Route as AuthenticatedPlacementLangRouteImport } from './routes/_authenticated/placement.$lang'
import { Route as AuthenticatedLessonIdRouteImport } from './routes/_authenticated/lesson.$id'
import { Route as AuthenticatedLearnLangRouteImport } from './routes/_authenticated/learn.$lang'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVocabLangRoute = AuthenticatedVocabLangRouteImport.update({
  id: '/vocab/$lang',
  path: '/vocab/$lang',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideosLangRoute = AuthenticatedVideosLangRouteImport.update({
  id: '/videos/$lang',
  path: '/videos/$lang',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideoIdRoute = AuthenticatedVideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlacementLangRoute =
  AuthenticatedPlacementLangRouteImport.update({
    id: '/placement/$lang',
    path: '/placement/$lang',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonIdRoute = AuthenticatedLessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnLangRoute = AuthenticatedLearnLangRouteImport.update({
  id: '/learn/$lang',
  path: '/learn/$lang',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/learn/$lang': typeof AuthenticatedLearnLangRoute
  '/lesson/$id': typeof AuthenticatedLessonIdRoute
  '/placement/$lang': typeof AuthenticatedPlacementLangRoute
  '/video/$id': typeof AuthenticatedVideoIdRoute
  '/videos/$lang': typeof AuthenticatedVideosLangRoute
  '/vocab/$lang': typeof AuthenticatedVocabLangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/learn/$lang': typeof AuthenticatedLearnLangRoute
  '/lesson/$id': typeof AuthenticatedLessonIdRoute
  '/placement/$lang': typeof AuthenticatedPlacementLangRoute
  '/video/$id': typeof AuthenticatedVideoIdRoute
  '/videos/$lang': typeof AuthenticatedVideosLangRoute
  '/vocab/$lang': typeof AuthenticatedVocabLangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/learn/$lang': typeof AuthenticatedLearnLangRoute
  '/_authenticated/lesson/$id': typeof AuthenticatedLessonIdRoute
  '/_authenticated/placement/$lang': typeof AuthenticatedPlacementLangRoute
  '/_authenticated/video/$id': typeof AuthenticatedVideoIdRoute
  '/_authenticated/videos/$lang': typeof AuthenticatedVideosLangRoute
  '/_authenticated/vocab/$lang': typeof AuthenticatedVocabLangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/learn/$lang'
    | '/lesson/$id'
    | '/placement/$lang'
    | '/video/$id'
    | '/videos/$lang'
    | '/vocab/$lang'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/learn/$lang'
    | '/lesson/$id'
    | '/placement/$lang'
    | '/video/$id'
    | '/videos/$lang'
    | '/vocab/$lang'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/learn/$lang'
    | '/_authenticated/lesson/$id'
    | '/_authenticated/placement/$lang'
    | '/_authenticated/video/$id'
    | '/_authenticated/videos/$lang'
    | '/_authenticated/vocab/$lang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vocab/$lang': {
      id: '/_authenticated/vocab/$lang'
      path: '/vocab/$lang'
      fullPath: '/vocab/$lang'
      preLoaderRoute: typeof AuthenticatedVocabLangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/videos/$lang': {
      id: '/_authenticated/videos/$lang'
      path: '/videos/$lang'
      fullPath: '/videos/$lang'
      preLoaderRoute: typeof AuthenticatedVideosLangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/video/$id': {
      id: '/_authenticated/video/$id'
      path: '/video/$id'
      fullPath: '/video/$id'
      preLoaderRoute: typeof AuthenticatedVideoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placement/$lang': {
      id: '/_authenticated/placement/$lang'
      path: '/placement/$lang'
      fullPath: '/placement/$lang'
      preLoaderRoute: typeof AuthenticatedPlacementLangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lesson/$id': {
      id: '/_authenticated/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof AuthenticatedLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$lang': {
      id: '/_authenticated/learn/$lang'
      path: '/learn/$lang'
      fullPath: '/learn/$lang'
      preLoaderRoute: typeof AuthenticatedLearnLangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedLearnLangRoute: typeof AuthenticatedLearnLangRoute
  AuthenticatedLessonIdRoute: typeof AuthenticatedLessonIdRoute
  AuthenticatedPlacementLangRoute: typeof AuthenticatedPlacementLangRoute
  AuthenticatedVideoIdRoute: typeof AuthenticatedVideoIdRoute
  AuthenticatedVideosLangRoute: typeof AuthenticatedVideosLangRoute
  AuthenticatedVocabLangRoute: typeof AuthenticatedVocabLangRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedLearnLangRoute: AuthenticatedLearnLangRoute,
  AuthenticatedLessonIdRoute: AuthenticatedLessonIdRoute,
  AuthenticatedPlacementLangRoute: AuthenticatedPlacementLangRoute,
  AuthenticatedVideoIdRoute: AuthenticatedVideoIdRoute,
  AuthenticatedVideosLangRoute: AuthenticatedVideosLangRoute,
  AuthenticatedVocabLangRoute: AuthenticatedVocabLangRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
